---
# Install python3-pip (needed if you install docker-compose via pip)
- name: Install python3-pip (for docker-compose)
  dnf:
    name: python3-pip
    state: present
    update_cache: yes

# Install Docker package(s)
- name: Install Docker packages
  dnf:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

# Ensure docker group exists (so useradd/append works)
- name: Ensure docker group exists
  group:
    name: docker
    state: present

# Start & enable Docker service
- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
  notify: restart docker

# Add user to docker group (optional; controlled by variable docker_user)
- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user != ""

- name: Ensure Docker CLI plugins directory exists
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose plugin
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.32.2/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'

